

server:
  port: 3200
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: inventory-service
        uri: http://localhost:3201/
        predicates:
        - Path=/inventory/**
      - id: driver-service
        uri: http://localhost:3202/
        predicates:
        - Path=/driver/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true